= Docker base images for Java web apps project


This project contains few Dockerfiles of  *Git*, *Maven*, *Java* and *New Relic* images I use in my project to develop, build, test and deploy *Spring Boot* applications.  

You can edit the Makefile to replace the name of the repo _*yakhyadabo*_ with your own docker repo. 

== How to use them : 

1. *Build/Push Java image*

The Java image is the root image, It's build using _Alpine Linux_ and _OpenJDK_. The other images are build on top of it.

To build it you can type one of the the commands below : 

 - _*make java-image-build <version>*_
 - _*make java-image-build*_ to user the default version _*alpine-openjdk-1.8.0*_
 

To publish it you can type one of the the commands below :

 - _*make java-image-push <version>*_
 - _*make java-image-push*_ to user the default version _*alpine-openjdk-1.8.0*_

// Here's an exemple of springboot project where you can find a use case.  

[start=2]
2. *New Relic image*

3. *Maven image*

4. *Maven-Git image*







// vim: set syntax=asciidoc:
